### ISSUE TITLE
Java Heap

### ISSUE THREAD

**Issue by Pawamoy** [Ecole-des-collegues/CriCriStatistics#20]
Clairement un problème de nettoyage de la mémoire.
Entre le moment où on fait des acquisitions et qu'on traite pas (index dans la DB) et le moment où on parse+stats+excel BIM y'a 2,5Go de mémoire bouffés

**Comment by Pawamoy** [comment]
> Exception in thread "Thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sun.net.www.http.ChunkedInputStream.processRaw(ChunkedInputStream.java:363)
	at sun.net.www.http.ChunkedInputStream.readAheadNonBlocking(ChunkedInputStream.java:520)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:611)
	at sun.net.www.http.ChunkedInputStream.available(ChunkedInputStream.java:725)
	at java.io.FilterInputStream.available(FilterInputStream.java:168)
	at sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:100)
	at java.util.Scanner.readInput(Scanner.java:804)
	at java.util.Scanner.next(Scanner.java:1369)
	at GenomeThread.getGenomeGenbanks(GenomeThread.java:170)
	at GenomeThread.run(GenomeThread.java:57)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Pawamoy** [comment]
> Exception in thread "Thread-5" java.lang.OutOfMemoryError: Java heap space
at java.io.Reader.read(Reader.java:99)
at java.util.Scanner.readInput(Scanner.java:804)
at java.util.Scanner.next(Scanner.java:1369)
at GenomeThread.getGenomeGenbanks(GenomeThread.java:168)
at GenomeThread.run(GenomeThread.java:57)
at java.lang.Thread.run(Thread.java:745)

**Comment by Pawamoy** [comment]
> Exception in thread "Thread-4" java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
at java.lang.StringBuilder.append(StringBuilder.java:136)
at GenomeThread.getGenomeGenbanks(GenomeThread.java:171)
at GenomeThread.run(GenomeThread.java:57)
at java.lang.Thread.run(Thread.java:745)

**Comment by Pawamoy** [comment]
Du coup c'est sûrement les scanners et/ou les string builder

**Comment by Pawamoy** [comment]
Je ferme le ticket, on rouvrira si besoin
